import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    page.setDefaultTimeout(180000);
    await page.goto('https://rims-demo.blubirch.com/');
    await page.getByRole('textbox', { name: 'Enter email ID/phone number/' }).click();
    await page.getByRole('textbox', { name: 'Enter email ID/phone number/' }).fill('brundadmin@yopmail.com');
    await page.getByRole('textbox', { name: 'Enter Password' }).click();
    await page.getByRole('textbox', { name: 'Enter Password' }).fill('blubirch@123');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByText('RIMS').click();
    await page.locator('v-list-item-content').filter({ hasText: /^Disposition$/ }).locator('div').click();
    await page.getByRole('link', { name: 'Liquidation Quantity 2055' }).click();
    // await page.locator('#input-238').check();
    // await page.locator("(//input[@type='checkbox'])[7]").click();
    const targetPrice = '7,000';
    await page.locator("//tr[td[normalize-space(text())='${targetPrice}']]//input[@type='checkbox']").first().click();
   await row.locator('input[type="checkbox"]').first().click();
    // await page.waitForTimeout(8000);
    await page.getByRole('button', { name: 'Other Action' }).click();
    await page.getByText('Mark As E-Waste').click();
    await page.getByRole('radio', { name: 'No' }).check();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('button', { name: 'Ok' }).click();
    // await page.locator('#input-295').check();
    await page.locator("(//input[@type='checkbox'])[2]").click();
    // await page.waitForTimeout(8000);
    await page.getByRole('button', { name: 'Allocation' }).click();
    await page.getByText('Allocate To B2B').click();
    await page.getByRole('button', { name: 'Submit' }).click();
    await page.getByRole('button', { name: 'Ok' }).click();
    await page.getByRole('tab', { name: 'Sales Method' }).click();
    // await page.locator('#input-416').check();
    await page.locator("(//input[@type='checkbox'])[2]").click();
    // await page.waitForTimeout(8000);
    test.setTimeout(120000); // 2 minutes
    await page.getByRole('button', { name: 'Select Action' }).click();
    await page.waitForTimeout(80000);
    await page.getByText('Competitive Bidding').click();
    await page.getByRole('button', { name: 'confirm' }).click();
    await page.getByRole('button', { name: 'Ok' }).click();
    await page.getByRole('tab', { name: 'Create Lots' }).click();
    await page.getByText('Competitive').click();
    // await page.locator('#input-485').check();
    await page.locator("(//input[@type='checkbox'])[2]").click();
    await page.getByRole('button', { name: 'Lot Creation' }).click();
    await page.getByText('Create Lot', { exact: true }).click();
    await page.getByRole('textbox', { name: 'Lot Name Lot Name' }).click();
    await page.getByRole('textbox', { name: 'Lot Name Lot Name' }).fill('Lot || Top Brand || 127 items || As in condition || Hyderabad || 237328374931353 || 18:45');
    await page.getByRole('textbox', { name: 'Lot Description Lot' }).click();
    await page.getByRole('textbox', { name: 'Lot Description Lot' }).fill('Lot || Top Brand || 127 items || As in Condition || Hyderabad || 237328374931353 || 18:45');
    await page.getByRole('textbox', { name: 'Bid Value to be Multiple of' }).click();
    await page.getByRole('option', { name: '1000', exact: true }).click();
    await page.getByRole('textbox', { name: 'Buy Now Price (₹) Buy Now' }).click();
    await page.getByRole('textbox', { name: 'Buy Now Price (₹) Buy Now' }).fill('5000');
    await page.getByRole('textbox', { name: 'Reserve Price (₹) Reserve' }).click();
    await page.getByRole('textbox', { name: 'Reserve Price (₹) Reserve' }).fill('4000');
    await page.getByRole('textbox', { name: 'Floor Price (₹) Floor Price' }).click();
    await page.getByRole('textbox', { name: 'Floor Price (₹) Floor Price' }).fill('2000');
    await page.getByRole('button', { name: 'Lot Images' }).click();
    await page.getByRole('dialog').locator('label i').click();
    // await page.locator('div').filter({ hasText: 'Select imagesCancelSubmit' }).nth(2).setInputFiles('71tbMyhmxcL.SL1500.jpg');
    // const fileInput = page.locator('div:has-text("Select images") input[type="file"]');
    // await fileInput.setInputFiles('C:\\Users\\Blubirch\\RIA-RIMS_Automation\\Usecase-3\\RIA_image\\ref_dent1.jpg');
    await page.getByRole('button', { name: 'Lot Images' }).click();
    const dialog = page.getByRole('dialog');
    const fileInput = dialog.locator('input[type="file"]');
    await fileInput.setInputFiles('C:\\Users\\Blubirch.DESKTOP-EN2LGLN\\Pictures\\img7.jpg');
    await page.getByRole('button', { name: 'Submit', exact: true }).click();
    await page.getByRole('textbox', { name: 'Bid Start Date Bid Start Date' }).click();
    await page.getByRole('button', { name: '26' }).click();
    await page.getByRole('button', { name: 'OK' }).click();
    await page.getByRole('textbox', { name: 'Bid Start Time Bid Start Time' }).click();
    // await page.getByRole('button', { name: '󰅃' }).nth(1).click();
    await page.getByRole('button', { name: '󰅃' }).first().click();
    await page.getByRole('button', { name: '󰅀' }).nth(2).click();
    await page.getByRole('button', { name: 'OK' }).click();
    await page.getByRole('textbox', { name: 'Bid End Date Bid End Date' }).click();
    await page.getByRole('button', { name: '26' }).click();
    await page.getByRole('button', { name: 'OK' }).click();
    await page.getByRole('textbox', { name: 'Bid End Time Bid End Time' }).click();
    // await page.getByRole('button', { name: '󰅀' }).nth(8).click();
    await page.getByRole('button', { name: '󰅃' }).first().click();
    await page.getByRole('button', { name: '󰅃' }).nth(4).click();
    await page.getByRole('button', { name: 'OK' }).click();
    await page.getByRole('spinbutton', { name: 'Enter the no. of days from' }).click();
    await page.getByRole('spinbutton', { name: 'Enter the no. of days from' }).fill('1');
    await page.getByRole('button', { name: 'SUBMIT' }).click();
    await page.getByRole('button', { name: 'Ok' }).click();
    await page.getByRole('tab', { name: 'Publish' }).click();
    await page.getByText('B2B').click();
    });